[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn certifier.wsgi:application"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[deploy.env]
PYTHON_VERSION = "3.11.0"
