services:
  - type: web
    name: certifier
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'adminpassword123') if not User.objects.filter(username='admin').exists() else None" | python manage.py shell
    startCommand: gunicorn certifier.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: certifier.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: certifier-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "adminpassword123"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
    autoDeploy: true
    dependencies:
      - name: certifier-db

databases:
  - name: certifier-db
    databaseName: certifier
    user: certifier
    plan: free
