services:
  - type: web
    name: certifier
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn certifier.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: certifier.settings
      - key: DATABASE_URL
        fromDatabase:
          name: certifier-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
    autoDeploy: true
    dependencies:
      - type: postgresql
        name: certifier-db
        plan: free

databases:
  - name: certifier-db
    databaseName: certifier
    user: certifier
    plan: free
