services:
  - type: web
    name: certifier
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      python manage.py create_superuser
      gunicorn certifier.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: certifier.settings
      - key: DATABASE_URL
        fromDatabase:
          name: certifier-db
          property: connectionString

databases:
  - name: certifier-db
    databaseName: certifier
    user: certifier
    plan: free
