# Generated by Django 5.2.1 on 2025-05-31 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='When the certificate expires (optional)', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the certificate becomes valid'),
        ),
    ]
