# Generated by Django 5.2.1 on 2025-05-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_end_date_certificate_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'Excellent (90-100%)'), ('B', 'Very Good (80-89%)'), ('C', 'Good (70-79%)'), ('D', 'Pass (60-69%)'), ('F', 'Fail (Below 60%)')], help_text="Student's grade in the course", max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numerical score (0-100)', max_digits=5, null=True),
        ),
    ]
