# Generated by Django 5.2.1 on 2025-05-31 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_grade_certificate_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='score',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Course end date', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='grade',
            field=models.TextField(blank=True, help_text="Student's grade in the course", null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Course start date'),
        ),
    ]
